# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-25 01:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Descriptor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descriptor_id', models.IntegerField()),
                ('descriptor_revision', models.IntegerField()),
                ('description', models.CharField(blank=True, max_length=1000, null=True)),
                ('dimension_symbol', models.CharField(blank=True, max_length=100, null=True)),
                ('creator', models.IntegerField()),
                ('modified_by', models.IntegerField()),
                ('creation_time', models.DateTimeField()),
                ('modified_time', models.DateTimeField()),
                ('approval_status', models.CharField(max_length=1)),
                ('deleted', models.IntegerField()),
            ],
            options={
                'managed': False,
                'db_table': 'descriptor',
            },
        ),
        migrations.CreateModel(
            name='DescriptorHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descriptor_id', models.IntegerField()),
                ('descriptor_revision', models.IntegerField()),
                ('description', models.CharField(blank=True, max_length=1000, null=True)),
                ('dimension_symbol', models.CharField(blank=True, max_length=100, null=True)),
                ('unit_name', models.CharField(blank=True, max_length=100, null=True)),
                ('creator_id', models.BigIntegerField()),
                ('modified_by', models.BigIntegerField()),
                ('creation_time', models.DateTimeField()),
                ('modified_time', models.DateTimeField()),
                ('approval_status', models.CharField(max_length=1)),
                ('deleted', models.IntegerField()),
            ],
            options={
                'managed': False,
                'db_table': 'descriptor_history',
            },
        ),
        migrations.CreateModel(
            name='DescriptorName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descriptor_name_number', models.IntegerField()),
                ('name', models.CharField(max_length=100)),
                ('name_language', models.CharField(max_length=2)),
                ('display_order', models.IntegerField()),
                ('preferred', models.IntegerField()),
            ],
            options={
                'managed': False,
                'db_table': 'descriptor_name',
            },
        ),
        migrations.CreateModel(
            name='DescriptorNameHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descriptor_id', models.BigIntegerField()),
                ('descriptor_revision', models.IntegerField()),
                ('descriptor_name_number', models.IntegerField()),
                ('name', models.CharField(max_length=100)),
                ('name_language', models.CharField(max_length=2)),
                ('display_order', models.IntegerField()),
                ('preferred', models.IntegerField()),
            ],
            options={
                'managed': False,
                'db_table': 'descriptor_name_history',
            },
        ),
        migrations.CreateModel(
            name='Dictionary',
            fields=[
                ('dictionary_id', models.IntegerField(primary_key=True, serialize=False)),
                ('creator', models.IntegerField()),
                ('creation_time', models.DateTimeField()),
                ('modified_time', models.DateTimeField()),
                ('deleted', models.IntegerField()),
            ],
            options={
                'managed': False,
                'db_table': 'dictionary',
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'managed': False,
                'db_table': 'django_migrations',
            },
        ),
        migrations.CreateModel(
            name='Folder',
            fields=[
                ('folder_id', models.IntegerField(primary_key=True, serialize=False)),
                ('folder_name', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, max_length=1000, null=True)),
                ('order_in_folder', models.IntegerField()),
                ('creator', models.IntegerField()),
                ('creation_time', models.DateTimeField()),
                ('modified_time', models.DateTimeField()),
                ('deleted', models.IntegerField()),
            ],
            options={
                'managed': False,
                'db_table': 'folder',
            },
        ),
        migrations.CreateModel(
            name='FolderDescriptor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_time', models.DateTimeField()),
            ],
            options={
                'managed': False,
                'db_table': 'folder_descriptor',
            },
        ),
        migrations.CreateModel(
            name='FolderPredictionModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_time', models.DateTimeField()),
            ],
            options={
                'managed': False,
                'db_table': 'folder_prediction_model',
            },
        ),
        migrations.CreateModel(
            name='FolderSoftwareTool',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_time', models.DateTimeField()),
            ],
            options={
                'managed': False,
                'db_table': 'folder_software_tool',
            },
        ),
        migrations.CreateModel(
            name='PredictionModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prediction_model_id', models.IntegerField()),
                ('prediction_model_revision', models.IntegerField()),
                ('description', models.CharField(blank=True, max_length=1000, null=True)),
                ('creator', models.IntegerField()),
                ('modified_by', models.IntegerField()),
                ('creation_time', models.DateTimeField()),
                ('modified_time', models.DateTimeField()),
                ('approval_status', models.CharField(max_length=1)),
                ('deleted', models.IntegerField()),
            ],
            options={
                'managed': False,
                'db_table': 'prediction_model',
            },
        ),
        migrations.CreateModel(
            name='PredictionModelDescriptor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descriptor_number', models.IntegerField()),
                ('in_or_out', models.CharField(max_length=1)),
                ('display_order', models.IntegerField()),
            ],
            options={
                'managed': False,
                'db_table': 'prediction_model_descriptor',
            },
        ),
        migrations.CreateModel(
            name='PredictionModelDescriptorHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prediction_model_id', models.BigIntegerField()),
                ('prediction_model_revision', models.IntegerField()),
                ('descriptor_number', models.IntegerField()),
                ('in_or_out', models.CharField(max_length=1)),
                ('descriptor_id', models.BigIntegerField()),
                ('display_order', models.IntegerField()),
            ],
            options={
                'managed': False,
                'db_table': 'prediction_model_descriptor_history',
            },
        ),
        migrations.CreateModel(
            name='PredictionModelHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prediction_model_id', models.IntegerField()),
                ('prediction_model_revision', models.IntegerField()),
                ('description', models.CharField(blank=True, max_length=1000, null=True)),
                ('prediction_model_type_code', models.IntegerField(blank=True, null=True)),
                ('creator_id', models.BigIntegerField()),
                ('modified_by', models.BigIntegerField()),
                ('creation_time', models.DateTimeField()),
                ('modified_time', models.DateTimeField()),
                ('approval_status', models.CharField(max_length=1)),
                ('deleted', models.IntegerField()),
            ],
            options={
                'managed': False,
                'db_table': 'prediction_model_history',
            },
        ),
        migrations.CreateModel(
            name='PredictionModelName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prediction_model_name_nubmer', models.IntegerField()),
                ('name', models.CharField(max_length=100)),
                ('name_language', models.CharField(max_length=2)),
                ('display_order', models.IntegerField()),
                ('preferred', models.IntegerField()),
            ],
            options={
                'managed': False,
                'db_table': 'prediction_model_name',
            },
        ),
        migrations.CreateModel(
            name='PredictionModelNameHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prediction_model_id', models.BigIntegerField()),
                ('prediction_model_revision', models.IntegerField()),
                ('prediction_model_name_nubmer', models.IntegerField()),
                ('name', models.CharField(max_length=100)),
                ('name_language', models.CharField(max_length=2)),
                ('display_order', models.IntegerField()),
                ('preferred', models.IntegerField()),
            ],
            options={
                'managed': False,
                'db_table': 'prediction_model_name_history',
            },
        ),
        migrations.CreateModel(
            name='PredictionModelTool',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('software_tool_number', models.IntegerField()),
                ('display_order', models.IntegerField()),
            ],
            options={
                'managed': False,
                'db_table': 'prediction_model_tool',
            },
        ),
        migrations.CreateModel(
            name='PredictionModelToolHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prediction_model_id', models.BigIntegerField()),
                ('prediction_model_revision', models.IntegerField()),
                ('software_tool_number', models.IntegerField()),
                ('software_tool_id', models.BigIntegerField()),
                ('display_order', models.IntegerField()),
            ],
            options={
                'managed': False,
                'db_table': 'prediction_model_tool_history',
            },
        ),
        migrations.CreateModel(
            name='PredictionModelType',
            fields=[
                ('prediction_model_type_code', models.IntegerField(primary_key=True, serialize=False)),
                ('prediction_model_type_name', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'managed': False,
                'db_table': 'prediction_model_type',
            },
        ),
        migrations.CreateModel(
            name='Quantity',
            fields=[
                ('quantity_name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('quantity_label', models.CharField(blank=True, max_length=100, null=True)),
                ('dimension_symbol', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'managed': False,
                'db_table': 'quantity',
            },
        ),
        migrations.CreateModel(
            name='SoftwareTool',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('software_tool_id', models.IntegerField()),
                ('software_tool_revision', models.IntegerField()),
                ('name', models.CharField(max_length=100)),
                ('name_language', models.CharField(max_length=2)),
                ('description', models.CharField(blank=True, max_length=1000, null=True)),
                ('license', models.CharField(blank=True, max_length=100, null=True)),
                ('version', models.CharField(blank=True, max_length=100, null=True)),
                ('platform', models.CharField(blank=True, max_length=100, null=True)),
                ('creator', models.IntegerField()),
                ('modified_by', models.IntegerField()),
                ('creation_time', models.DateTimeField()),
                ('modified_time', models.DateTimeField()),
                ('approval_status', models.CharField(max_length=1)),
                ('deleted', models.IntegerField()),
            ],
            options={
                'managed': False,
                'db_table': 'software_tool',
            },
        ),
        migrations.CreateModel(
            name='SoftwareToolDescriptor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descriptor_number', models.IntegerField()),
                ('in_or_out', models.CharField(max_length=1)),
                ('display_order', models.IntegerField()),
            ],
            options={
                'managed': False,
                'db_table': 'software_tool_descriptor',
            },
        ),
        migrations.CreateModel(
            name='SoftwareToolDescriptorHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('software_tool_id', models.BigIntegerField()),
                ('software_tool_revision', models.IntegerField()),
                ('descriptor_number', models.IntegerField()),
                ('in_or_out', models.CharField(max_length=1)),
                ('descriptor_id', models.BigIntegerField()),
                ('display_order', models.IntegerField()),
            ],
            options={
                'managed': False,
                'db_table': 'software_tool_descriptor_history',
            },
        ),
        migrations.CreateModel(
            name='SoftwareToolHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('software_tool_id', models.IntegerField()),
                ('software_tool_revision', models.IntegerField()),
                ('name', models.CharField(max_length=100)),
                ('name_language', models.CharField(max_length=2)),
                ('description', models.CharField(blank=True, max_length=1000, null=True)),
                ('license', models.CharField(blank=True, max_length=100, null=True)),
                ('version', models.CharField(blank=True, max_length=100, null=True)),
                ('platform', models.CharField(blank=True, max_length=100, null=True)),
                ('creator_id', models.BigIntegerField()),
                ('modified_by', models.BigIntegerField()),
                ('creation_time', models.DateTimeField()),
                ('modified_time', models.DateTimeField()),
                ('approval_status', models.CharField(max_length=1)),
                ('deleted', models.IntegerField()),
            ],
            options={
                'managed': False,
                'db_table': 'software_tool_history',
            },
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('unit_name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('unit_label', models.CharField(blank=True, max_length=100, null=True)),
                ('unit_symbol', models.CharField(max_length=100)),
            ],
            options={
                'managed': False,
                'db_table': 'unit',
            },
        ),
    ]
