# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-18 05:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dumpviewer', '0002_graph'),
    ]

    operations = [
        migrations.AddField(
            model_name='graph',
            name='parameterString',
            field=models.TextField(default=None),
        ),
    ]
