# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-19 05:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dumpviewer', '0003_graph_parameterstring'),
    ]

    operations = [
        migrations.AddField(
            model_name='graph',
            name='graphsString',
            field=models.TextField(default=None),
        ),
    ]
