# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-19 05:45
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('dumpviewer', '0004_graph_graphsstring'),
    ]

    operations = [
        migrations.AddField(
            model_name='graph',
            name='identifier',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
