# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-19 05:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dumpviewer', '0005_graph_identifier'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='graph',
            name='identifier',
        ),
    ]
