# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-19 06:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dumpviewer', '0006_remove_graph_identifier'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='graph',
            name='id',
        ),
        migrations.AddField(
            model_name='graph',
            name='identifier',
            field=models.AutoField(default=None, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
