# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-16 06:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dumpviewer', '0008_graph_timestamp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='graph',
            name='timestamp',
        ),
    ]
