# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-16 06:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dumpviewer', '0010_graph_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='graph',
            name='timestamp',
            field=models.CharField(max_length=100),
        ),
    ]
